---
title: Problemas 4
subtitle: Composición iterativa
format: html
draft: true
---

## Seguimiento de la ejecución de un bucle

Escribe la secuencia de **números de línea** que se ejecutarán en el siguiente bucle `while`:

- 1, 2, 3, ...

```python
count = 1
while count <= 3:
    print(count)
    count += 1
print("Fin")
```

<details>
<summary>Solución</summary>

| 1, 2,        _(evalua como True)_
| 3, 4, 2,     _(evalua como True)_
| 3, 4, 2      _(evalua como True)_
| 3, 4, **2**  _(evalua como False)_
| 5

**Fíjate** que la línea `2` se ejecuta **también** al final de la última iteración.

</details>


---

## ¿Está seguro de que desea eliminar el archivo?

Escribe un programa en Python que solicite al usuario una respuesta y determine si está seguro de eliminar un archivo.
El programa debe aceptar las respuestas `s`, `n`, `si` y `no`.
Si la respuesta no es ninguna de las anteriores, el programa repetirá la pregunta hasta que se introduzca una respuesta válida.

| ¿Está seguro de que desea eliminar el archivo? (s)i/(n)o:
| **yeppers**
| ¿Está seguro de que desea eliminar el archivo? (s)i/(n)o:
| **s**
| ARCHIVO ELIMINADO

| ¿Está seguro de que desea eliminar el archivo? (s)i/(n)o:
| **n**
| SKIP

<details>
<summary>Solución</summary>

```python
correcto = False

while not correcto:
    print("¿Está seguro de que desea eliminar el archivo? (s)i/(n)o:")
    respuesta = input()

    if respuesta == "s" or respuesta == "si":
        print("ARCHIVO ELIMINADO")
        correcto = True
    elif respuesta == "n" or respuesta == "no":
        print("SKIP")
        correcto = True
```

</details>

## Sumar una secuencia

Escribe un programa en Python que solicite iterativamente una secuencia de números enteros. Dicha secuencia terminará cuando el usuario introduzca un número negativo. El programa debe sumar todos los números introducidos y mostrar el resultado.

| Introduce un número entero:
| **1**
| Introduce un número entero:
| **2**
| Introduce un número entero:
| **3**
| Introduce un número entero:
| **-1**
| La suma de los números es:
| 6

<details>
<summary>Solución</summary>

```python
suma = 0
numero = 0

while numero >= 0:
    print("Introduce un número entero:")
    numero = int(input())

    if numero >= 0:
        suma = suma + numero

print("La suma de los números es:")
print(suma)
```

</details>

## Sumar las cifras de un número

Escribe un programa en Python que solicite al usuario un número entero de `n` cifras y que sume todas las cifras de dicho número.

| Introduce un número entero:
| **123**
| La suma de las cifras es:
| 6

<details>
<summary>Solución</summary>

```python
print("Introduce un número de tres cifras:")
numero = int(input())

numero_restante = numero
suma = 0

while numero_restante > 0:
    unidades = numero % 10
    numero_restante = numero // 10
    suma = suma + unidades

print("La suma de las cifras es:")
print(suma)
```

</details>
