---
title: Problemas 5
subtitle: 'Composición iterativa: for y while'
format: html
draft: true
---

## Media de una secuencia de enteros

Escribe un programa en Python que solicite al usuario una secuencia de números enteros positivos (terminada en 0) y que calcule la media de los números introducidos.
Si el número introducido es negativo, el programa debe ignorarlo y seguir solicitando números.

| Introduce un número entero:
| **2**
| Introduce un número entero:
| **-4**
| Introduce un número entero:
| **4**
| Introduce un número entero:
| **-1**
| Introduce un número entero:
| **0**
| La media de los números es: 3.0


<details>
<summary>Solución</summary>

```python
suma = 0
contador = 0

numero = 1
while numero != 0:
    print("Introduce un número entero:")
    numero = int(input())

    if numero > 0:
        suma += numero
        contador += 1

media = suma / contador
print(f"La media de los números es: {media}")
```

</details>

## Potencia enésima

Escribe un programa en Python que solicite al usuario dos números enteros positivos `base` y `exponente` y que calcule la potencia enésima de `base` elevado a `exponente`.
**El programa debe comprobar que `base` sea mayor estricto que cero y `exponente` sea mayor o igual que cero.**

| Introduce la base:
| **2**
| Introduce el exponente:
| **3**
| 2^3 = 8

| Introduce la base:
| **0**
| Introduce la base (mayor que 0):
| **2**
| Introduce el exponente:
| **-2**
| Introduce el exponente (mayor o igual que 0):
| **3**
| 2^3 = 8

<details>
<summary>Solución</summary>

```python
print("Introduce la base:")
base = int(input())
while base <= 0:
    print("Introduce la base (mayor que 0):")
    base = int(input())

print("Introduce el exponente:")
exponente = int(input())
while exponente < 0:
    print("Introduce el exponente (mayor o igual que 0):")
    exponente = int(input())

resultado = 1
for i in range(exponente):
    resultado *= base

print(f"{base}^{exponente} = {resultado}")
```

</details>

## Caja de NxM

Escribe un programa en Python que solicite al usuario dos números enteros positivos `n` y `m` y que dibuje una caja de `n` filas y `m` columnas. Las líneas horizontales se representarán con el caracter `-` (menos), las verticales con el caracter `|` (barra vertical) y las esquinas con el caracter `+` (más).

| Introduce el número de filas:
| **3**
| Introduce el número de columnas:
| **3**
| +---+
| |   |
| |   |
| |   |
| +---+

| Introduce el número de filas:
| **3**
| Introduce el número de columnas:
| **7**
| +-------+
| |       |
| |       |
| |       |
| +-------+

## Triángulo de caracteres

Escribe un programa en Python que solicite al usuario un carácter y un número entero positivo `n` y que dibuje un triángulo de `n` filas con el carácter introducido.

| Introduce un carácter:
| **x**
| Introduce un número entero:
| **3**
| x
| xx
| xxx

| Introduce un carácter:
| **o**
| Introduce un número entero:
| **5**
| o
| oo
| ooo
| oooo
| ooooo

<details>
<summary>Solución</summary>

```python
print("Introduce un carácter:")
caracter = input()
print("Introduce un número entero:")
n = int(input())

for i in range(1, n+1):
    for j in range(0, i):
        print(caracter, end="")
    print()
```

</details>
